name: CI
on:
  push:
    branches:
      - **
      - !master
      - !source
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies 📦
      run: yarn
    - name: Lint 🧹
      run: yarn lint
